### ISSUE TITLE
Email Subscriptions module no longer deactivates existing subscriptions with unsubscribe

### ISSUE THREAD

**Issue by HSCMSMigrations** [HubSpot/cms-theme-boilerplate#147]
In the themes boilerplate, the email subscription module has different functionality than the old vast templates. When you select "unsubscribe from all emails" in the vast template, the existing options are greyed out and unable to be selected. In the new templates these remain selected and unchanged. 

![Screen Shot 2020-05-01 at 10 59 37 AM](https://user-images.githubusercontent.com/60663090/80815059-fcc1b880-8b9a-11ea-9cba-1d5a766cee11.png)
![Screen Shot 2020-05-01 at 10 59 24 AM](https://user-images.githubusercontent.com/60663090/80815066-fdf2e580-8b9a-11ea-9cdc-34d79274f79a.png)

Here is the code that I have used to fix this in case you would like to use it:
```
This is added to the systems_pages.css
.email-prefs .item.disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.email-prefs .item.disabled input:disabled {
  cursor: not-allowed;
}
This is added to the main.js file
$('input[name="globalunsub"]').change(function () {
    if ($(this).is(':checked')) {
      $('.item').addClass('disabled')
      $('.item input').attr('disabled', 'disabled')
      $('.item input').removeAttr('checked')
    }
    else {
      $('.item').removeClass('disabled')
      $('.item input').removeAttr('disabled')
    }
  });
```

**Comment by jasonnrosa** [comment]
This was fixed up with this PR (https://github.com/HubSpot/cms-theme-boilerplate/pull/316).
