### ISSUE TITLE
Account for image max-width where necessary

### ISSUE THREAD

**Issue by ckconant** [HubSpot/cms-theme-boilerplate#149]
### Problem
Historically we've used `img {max-width: 100%}` in the migrations boilerplate. Since updating the image module's options to give customers more control over their images, we've had to remove the max-width so that the module can work freely. In doing so, we're not accounting for other modules allow image insertion.

### Possible ways to add images
- Image module
- Logo module
- Rich text module
- Blog content module (Rich text)
- Blog listings (if included above the 'Read more'
- Blog author image
- Featured images
- Rss listing
- Custom modules using an image field

### Possible solutions
There are several ways that we can account for max-width on images where we need it applied. Initially, my thought was to use a `not:()` pseudo selector for the image module, but we need to also account for any custom modules using an image field to omit the max-width from them as well. Since there isn't a good way to account for the image field, we may need to think through all of the possible ways to add images and use a class from each.

**Comment by jasonnrosa** [comment]
I pulled this from the 1.3 version project board for now. I'd like to get an update out fairly soon with the improvements for performance and page speed and I'd like to do a bit more testing/planning with this. I think the best path forward, like you had mentioned is something like: 

```
img {
  max-width: 100%; 
  height: auto; 
}

.hs_cos_wrapper_type_linked_image img {
  max-width: none; 
}
```

but I'd just want to think through how we'd approach our custom modules in this case a bit more (e.g. custom modules wouldn't have the image module wrapper class so would we want to add a specific utility class to all images that have image resizing turned on?).
