### ISSUE TITLE
Update deploy script to use environment variables

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/cms-theme-boilerplate#199]
With the addition of https://github.com/HubSpot/hubspot-cms-tools/pull/118, you can now pass config values as environment variables instead of creating a [config file](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/bin/generate-config.js), which would simplify deployment

**Comment by williamspiro** [comment]
https://github.com/HubSpot/hubspot-cms-tools/issues/270 would be 🆒 as well

**Comment by jasonnrosa** [comment]
Update - we should switch over to the new HubSpot CMS deploy action. Documentation here: (https://github.com/marketplace/actions/hubspot-cms-deploy).
