### ISSUE TITLE
Update file extensions

### ISSUE THREAD

**Issue by anthmatic** [HubSpot/cms-theme-boilerplate#242]
In an effort to make it easier to understand which files contain/support HubL, we'd like to try updating the file names. This wouldn't actually change anything, it's just a potential best practice to explore.

`.html` -> `.hubl.html`
`.css` -> `.hubl.css`

**Comment by adesignl** [comment]
backwards compatible? like twigg files?

**Comment by anthmatic** [comment]
> backwards compatible? like twig files?

@adesignl  I just updated the example (I had it backwards). There's actually no change in how these files will work when you upload them, so 100% compatible with the way things work today.

**Comment by adesignl** [comment]
There ya go.. I thought you were speaking of changing the syntax. lol 😄

**Comment by jasonnrosa** [comment]
Going to close this out in favor of #392 which is basically the same ask - the updates will live on the branch mentioned in that issue.
