### ISSUE TITLE
Add viewport meta tag

### ISSUE THREAD

**Issue by WilliamWard074** [HubSpot/cms-theme-boilerplate#258]
An SEO report flagged the following is needed in `base.html`

`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by jasonnrosa** [comment]
Hey @WilliamWard074 thank you for reporting! It looks like `<meta name="viewport" content="width=device-width, initial-scale=1.0">` is included as part of the `{{ standard_header_includes }}` HubL variable. There is a bit more detail [here](https://developers.hubspot.com/docs/cms/hubl/variables#required-page-template-variables) that goes over what the two required header/footer include variables pull in. I'll add a comment in the `base.html` file that links to this documentation.
