### ISSUE TITLE
Accordion module

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/cms-theme-boilerplate#295]
**Is your feature request related to a problem? Please describe.**

I very frequently see accordion modules that are inaccessible via keyboard and provide nothing for screen readers to be able to understand them.

**Describe the solution you'd like**

New boilerplate module built using details/summary html elements with very basic styling applied. This will give developers a base to build from that is accessible by default.

We can honestly steal code from my old code gallery submission. It will require some tweaks, but it gets us 90% of the way there.
https://designers.hubspot.com/code-gallery/entry/founders/TheWebTech-HS-Accessible-FAQ-Module

I think this is a good candidate for a boilerplate module since accordion modules often get significantly tweaked visuals per site. Providing a solid foundation for developers to build on seems like a good idea.

**Comment by jasonnrosa** [comment]
Hey, @TheWebTech 👋🏼 going to close this one out as this is something we are considering for a default module that can then be leveraged within the boilerplate. Let me know if you have any questions/concerns!
