### ISSUE TITLE
Pricing page - Buy now buttons

### ISSUE THREAD

**Issue by TanyaScales** [HubSpot/cms-theme-boilerplate#300]
## Description

All of the button text is the same for the pricing cards. Since a screen reader can navigate through the buttons of a page only using the rotor function, these buttons don't explain well enough what the user would be buying. Suggested fix: Change each button to reflect the package they would be buying. Ex. Buy 'Starter' Now, Buy 'Professional' Now, Buy 'Enterprise' Now

<img width="264" alt="Screen Shot 2020-12-16 at 1 36 26 PM" src="https://user-images.githubusercontent.com/4976331/102391435-b68f5d00-3fa3-11eb-9dc7-84b1e460159d.png">

**Comment by ckconant** [comment]
@TanyaScales just to clarify - is this specific to the template?

**Comment by TanyaScales** [comment]
> @TanyaScales just to clarify - is this specific to the template?

Sorry for the delay in response here, it was specifically the default content set at the template level
