### ISSUE TITLE
Explore using a more modern grid layout (e.g. Bootstrap 5) 

### ISSUE THREAD

**Issue by jasonnrosa** [HubSpot/cms-theme-boilerplate#319]
**Is your feature request related to a problem? Please describe.**

We are currently using an older version of Bootstrap (Bootstrap 2). 

**Describe the solution you'd like**

Use a more modern version of Bootstrap such as Bootstrap 5. 

**Checklist**

- [X] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [X] I have checked the [issue tracker](https://github.com/HubSpot/cms-theme-boilerplate/issues) to make sure there isn’t already an open issue.

**Comment by johnsfuller** [comment]
For what it's worth, [Bootstrap 5](https://getbootstrap.com/) is out now, but the dadgum [grid.css file](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap-grid.css) is 5000 lines long.

**Comment by jasonnrosa** [comment]
True good point (will update the issue). I think in general we should explore using a grid with `flex` vs. `float` so we can likely cut down on the `grid.css` file to just keep what we need and add on pieces as needed.

**Comment by stefenphelps** [comment]
I [wrote about the two ways I've updated the grid.css](https://stefenphelps.com/posts/custom-grid-gutters-on-hubspot/ ) this with flex box and css grid. It's fairly simple but I suppose the question what browsers do you all still want to support? In both of my examples I use the `gap` property which was only recently added to iOS (last year with the iOS 14.1 update).

**Comment by jasonnrosa** [comment]
Thanks @stefenphelps, I love the look of your `grid.css` that you linked!

> I suppose the question is what browsers do you all still want to support?

I think that conversation is still ongoing a bit. I think once we can nail that down we'll be able to start moving forward more on this item in particular and a couple of the open IE11 related items that we still need to address.
