### ISSUE TITLE
Main Element in Templates

### ISSUE THREAD

**Issue by jevenson** [HubSpot/cms-theme-boilerplate#361]
I noticed that every template has this as the first line of the body block

```html
{# The main-content ID is used for the navigation skipper in the header.html file. More information on the navigation skipper can be found here: https://github.com/HubSpot/cms-theme-boilerplate/wiki/Accessibility #}
<main id="main-content" class="body-container-wrapper">
```

Would it make sense to move this to the `layouts/base.html` to eliminate the duplicate code?

**Comment by jasonnrosa** [comment]
Great call out 👍🏼  yes I think that makes perfect sense to do!

**Comment by johnsfuller** [comment]
To play devil's advocate... what if I want a `<main></main><aside></aside>` markup in the body block? Not possible when you move main to `base.html`

**Comment by jasonnrosa** [comment]
Hey @johnsfuller I think that is a fair point. Given most of the content within boilerplate pages (outside of the blog post template right now) is drag and drop, would you see this as a common issue or do you think it is reasonable to assume someone could use `aside` within the `main` element somewhere (e.g. this would mean that `aside` would likely be included as part of a module unless the `aside` would be included outside of the main DND area)?

**Comment by jasonnrosa** [comment]
Just a note: going to move this out of the v3 project board for now to allow for more discussion. Generally speaking this shouldn't be a breaking change so it could be included in a future minor version.

**Comment by johnsfuller** [comment]
I'd need an accessibility expert and html markup expert to tell me the difference b/t `aside` as a descendant of `main` and `aside` as a descendent of `body`. 

However, to achieve the `<main></main><aside></aside>` markup previously discussed, I guess a dev could add a `{% block aside %}` block underneath the main tag.

```
<main>
  {% block body %}
  {% endblock body %}
</main>

{% block aside %}{% endblock aside %}
```

**Comment by TanyaScales** [comment]
> I'd need an accessibility expert and html markup expert to tell me the difference b/t `aside` as a descendant of `main` and `aside` as a descendent of `body`.

The difference is the association made between the content in the `<aside>` and where it lives. If you have the `<aside>` within the `<main>` area, you're trying to show that "This content is related to the content within the `<main>` area. Whereas, if you put it adjacent to the `<main>` tag you're saying that the content in the `<aside>` doesn't have a relationship to the content in the main area (thinking of examples such as sidebar areas with advertisements).
