### ISSUE TITLE
Create branch for Developer Projects starting point

### ISSUE THREAD

**Issue by TanyaScales** [HubSpot/cms-theme-boilerplate#392]
**Is your feature request related to a problem? Please describe.**

In order to support developers with using the CMS Boilerplate as well as Developer Projects, we want to create a starting point that they can go to and spin it up quickly.

**Describe the solution you'd like**

We'd like to create a permanent branch in the repo the is specifically for this purpose that houses the correct structure for Developer Projects with the CMS Boilerplate in the `theme` directory. Suggested branch name: `cms-boilerplate-developer-projects`

**Additional context**

For now, the `app` folder of the project should stay empty

**Checklist**

- [x] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [x] I have checked the [issue tracker](https://github.com/HubSpot/cms-theme-boilerplate/issues) to make sure there isn’t already an open issue.

**Comment by jasonnrosa** [comment]
I tossed up a branch for this. One concern/question I would have is that for this change we move essentially all theme files into a new folder so all files will move. I haven't messed around with branches enough to know if it will continue to pick up sub-sequential updates to say `src/fields.json` now that the file is moved to `src/theme/fields.json` in this case. I have a couple updates we can test to verify though.

**Comment by jasonnrosa** [comment]
Alright this is pretty much good to go - running into a few issues when testing that I will report but besides that I think the actual work here is done.

**Comment by jasonnrosa** [comment]
Just an adjustment here - we will be moving forward without the `theme` folder and will be omitting `hsproject.json`. We'll essentially be keeping the same folder structure and just be swapping files with HubL over to `.hubl.` extensions.

**Comment by jasonnrosa** [comment]
Going to close this out given the branch is ready (#404) but it won't be merged so this would be considered done for the time being.
