### ISSUE TITLE
CLI does not recognise @extends throwing Error validating template.

### ISSUE THREAD

**Issue by yumyo** [HubSpot/cms-theme-boilerplate#394]
We developed a theme following the official CMS Boilerplate https://github.com/HubSpot/cms-theme-boilerplate
Since upgrading the CLI to 3.0.9 it seems {% extends './layouts/base.html' %} is no longer recognised and the CLI prevent the upload and throws the following errors:
[ERROR] line 0: Template does not include the tag {{ standard_header_includes }}.
[ERROR] line 0: Template does not include the tag {{ standard_footer_includes }}. Needed for HubSpot analytics

## Update
Weirdly enough, the error appears only if I change the template label

**Comment by yumyo** [comment]
UPDATE
Weirdly enough, the error appears only if I change the template label

**Comment by jasonnrosa** [comment]
Hey @yumyo I can't seem to reproduce what you're seeing on my end. Would you be able to send along your theme files (feel free to send these via a direct message in the developer Slack if you'd prefer those to be kept private)? Some additional things I'd want to check:

- Is this issue happening for all of your templates or just some? 
- Assuming this is the case but confirming that standard_header_includes and standard_footer_includes are being added via base.html or elsewhere on the template
- Is the file path to the base.html correct in the template that has an issue (e.g. if a template file was placed in an additional folder the path may need to be adjusted)?

**Comment by jasonnrosa** [comment]
Hey @yumyo just wanted to check up on this - are you still running into this issue?

**Comment by jasonnrosa** [comment]
Hey @yumyo I'm going to close this out as I haven't heard back and I can't reproduce the issue on my end but please feel free to reach out if you're still running into any problems!
