### ISSUE TITLE
Update theme label in theme.json to use sentence casing

### ISSUE THREAD

**Issue by jasonnrosa** [HubSpot/cms-theme-boilerplate#411]
Update the theme label in the `theme.json` file to use sentence casing to match style guide/Canvas. Sentence casing would mean "Boilerplate theme" as opposed to title casing which would be "Boilerplate Theme"

**Comment by ckconant** [comment]
@jasonnrosa is the `theme.json` label considered a title? I've aways found obscurity in the canvas typography guidelines around casing:
- Sentence casing is most commonly used, with title casing being generally reserved for headings only

It is a small nit, and I personally love sentence casing, but curious of _when_ to use title casing...

**Comment by jasonnrosa** [comment]
@ckconant we still need to chat about this one a bit more internally but the more detailed canvas writing details have:
- Headers: Title case
- Subheaders: Sentence case

In this specific case, the theme label is most often used as a subheader in app vs. an h1/main header which is why we might be leaning towards changing it to sentence casing.

**Comment by ckconant** [comment]
Totally makes sense. Like I said, just a nit.

Also, Headings* 😉

**Comment by jasonnrosa** [comment]
Closed per (https://github.com/HubSpot/cms-theme-boilerplate/pull/430)
