### ISSUE TITLE
Vertically align adjacent field content in Page Editor

### ISSUE THREAD

**Issue by heykenneth** [HubSpot/cms-theme-boilerplate#424]
After setting display width to "half_width" in fields.json on a module, the contents of the field column do not align to the top of their container in the Page Editor sidebar.

`"display_width": "half_width"`

Setting the helper class on `.EditForm__TwoColumnsFieldWrapper `to `vertical-align: top;`, properly aligns the contents of the field column to the top of their container, improving readability.  

![image](https://user-images.githubusercontent.com/3528508/164482408-4c97bdc5-8aba-4c72-9820-3a9c40cd73be.png)

##### Device Info:

- Mac iOS, Monterey v12.3.1
- Chrome, v100.0.4XXX.XX

**Comment by ajlaporte** [comment]
Hi @heykenneth, thank you for reporting this issue. Would you be able to report this to our internal in-app support? This issue appears to be related more to the in-app experience (with how `display_width`'s are shown) and not directly to the boilerplate itself. Thanks again for the heads up on this.
