### ISSUE TITLE
Add new required theme settings (form fields) for marketplace submission

### ISSUE THREAD

**Issue by puresanfran** [HubSpot/cms-theme-boilerplate#455]
**Is your feature request related to a problem? Please describe.**

Our developer documentation now states the following for [required theme settings](https://developers.hubspot.com/docs/cms/marketplace-guidelines/theme-requirements#theme-fields) (fields) with regard to forms: 

- **Title background (missing)**
- Title text, including at least font color styles
- **Form background color (missing)**
- **Form border color (missing)**
- Form label color
- Form field border color
- **Form button, including settings for both button text, background color, and hover styling (missing)**

The boilerplate is missing 4 bolded above.

**Describe the solution you'd like**

We should go in and add these theme settings (fields) to the boilerplate.

**Checklist**

- [x] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [x] I have checked the [issue tracker](https://github.com/HubSpot/cms-theme-boilerplate/issues) to make sure there isn’t already an open issue.

**Comment by jazzyclimber** [comment]
@puresanfran This has been merged into main and will be released with some additional updates likely this week. #461

**Comment by jazzyclimber** [comment]
@puresanfran These edits have been pushed live https://github.com/HubSpot/cms-theme-boilerplate/releases/tag/v3.9.0

**Comment by puresanfran** [comment]
@jazzyclimber Thank you!
