### ISSUE TITLE
Incorporate `hs lint` into the lint action

### ISSUE THREAD

**Issue by gcorne** [HubSpot/cms-theme-boilerplate#64]
To get a better feel for the value of the somewhat experimental `hs lint` command, we should try and integrate it with the boilerplate via the Github action.

cc @corymartin

**Comment by gcorne** [comment]
I played around with the lint command, and it isn't very helpful due to how it works on the backend right now when a template extends another template. I think we'll need to somehow improve it before adding it to the boilerplate is useful.

**Comment by jasonnrosa** [comment]
Going to close this out for now because I think it is referencing a CLI command that no longer exists.
