### ISSUE TITLE
Add a sample hubspot config yml file to the repo 

### ISSUE THREAD

**Issue by axellabs** [HubSpot/cms-theme-boilerplate#66]
This will make general setup, and keeping up with config schema changes, much easier.

**Comment by gcorne** [comment]
@axellabs do you think that https://github.com/HubSpot/hubspot-cms-tools/issues/3 covers this or is there additional value in having a sample config in this repo?

**Comment by gcorne** [comment]
I think we should leverage `hs init` and `hs config` (when `hs config` is implemented).
