### ISSUE TITLE
Document how to set up GitHub Action

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/cms-theme-boilerplate#67]
Document how to set the deploy GitHub action up in a new repository.

**Comment by beacondigitalmarketing** [comment]
Are you talking about a GitHub action? Just set this up on my team!  I will contribute our documentation

**Comment by williamspiro** [comment]
@beacondigitalmarketing exactly! My thought is to essentially document:

1. That this sample project is set up to deploy to a portal when you merge to master
2. What you need to do to set this up for your own repository/portal when using the Boilerplate as a starting point.

**Comment by chaffeqa** [comment]
May be addressed in #98

**Comment by williamspiro** [comment]
https://designers.hubspot.com/tutorials/github-integration

**Comment by jasonnrosa** [comment]
Fixed via: https://github.com/HubSpot/cms-theme-boilerplate/pull/98 - will also add this content over to the Wiki now 👍
