### ISSUE TITLE
Footer social icons are invisible on hover 

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/cms-theme-boilerplate#97]
<img width="1188" alt="Screen Shot 2020-03-25 at 11 55 21 AM" src="https://user-images.githubusercontent.com/35824747/77557027-a1135980-6e8f-11ea-8e16-06ac3c00823f.png">

**Comment by jasonnrosa** [comment]
Fixed via this pull request (https://github.com/HubSpot/cms-theme-boilerplate/pull/112)
